install: true
git:
  submodules: false
cache:
  directories:
    - .build/checkouts # SwiftPM
    - .build/repositories # SwiftPM
branches:
  only:
    - master
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script: make test
      env: JOB=CI_TEST
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - make swiftpm_test
      env: JOB=CI_TEST_SWIFTPM
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - brew uninstall carthage
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install bats
        - make install
        - bats IntegrationTests
      env:
        - JOB=CI_INTEGRATION_TESTS
    - os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - brew uninstall carthage
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install bats
        - make swiftpm_install
        - bats IntegrationTests
      env:
        - JOB=CI_INTEGRATION_TESTS_SWIFTPM
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script: make test
      env: JOB=CI_TEST
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script:
        - make swiftpm_test
      env: JOB=CI_TEST_SWIFTPM
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script:
        - brew uninstall carthage
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install bats
        - make install
        - bats IntegrationTests
      env:
        - JOB=CI_INTEGRATION_TESTS
    - os: osx
      language: objective-c
      osx_image: xcode9.2
      script:
        - brew uninstall carthage
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install bats        
        - make swiftpm_install
        - bats IntegrationTests
      env:
        - JOB=CI_INTEGRATION_TESTS_SWIFTPM
notifications:
  email: false
  slack:
    secure: lblNhCx6581hiPskQQnH663QY/HHqs6y8rMCLIff1Ryq0ngBaTwBJZ6E5tAR8oWTGWg3nMAAm/AaJPQGFC9jnKxtpWJhuEF58RY+EBe1Rz3gjKmacvEZS+PW+k3cRrRPZr6Vh6D8d0cb1gfM7BvGZar21ipBC/WcnNden3LxZ+0=
